language: php
sudo: false
cache:
  apt: true

php:
    - 7.1

before_script:
    - cp config/autoload/local.php.dist config/autoload/local.php
    - ls config/autoload
    - composer install -o --prefer-dist
    - php -S 127.0.0.1:8080 -t public >/dev/null 2>&1 &

script:
    - vendor/bin/codecept run

